spring:
  datasource:
    username: root
    password: 808566as
    url: jdbc:mysql://127.0.0.1:3306/udbh?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    database: 0
    host: localhost
    password: 808566as
    timeout: 1000

server:
  port: 8088
  servlet:
    context-path: /udbh

